/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ListMultiplicator {
        "multiplicator": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface RecipeIngredients {
        "multiplicator": number;
    }
    interface RecipePage {
        "five": string;
        "four": string;
        "image": string;
        "one": string;
        "three": string;
        "title": string;
        "two": string;
    }
    interface SidebarListItem {
        "kind": string;
        "setMultiplicator": (m: number) => Promise<void>;
        "unit": string;
        "unitValue": number;
    }
    interface TopNav {
    }
}
declare global {
    interface HTMLListMultiplicatorElement extends Components.ListMultiplicator, HTMLStencilElement {
    }
    var HTMLListMultiplicatorElement: {
        prototype: HTMLListMultiplicatorElement;
        new (): HTMLListMultiplicatorElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRecipeIngredientsElement extends Components.RecipeIngredients, HTMLStencilElement {
    }
    var HTMLRecipeIngredientsElement: {
        prototype: HTMLRecipeIngredientsElement;
        new (): HTMLRecipeIngredientsElement;
    };
    interface HTMLRecipePageElement extends Components.RecipePage, HTMLStencilElement {
    }
    var HTMLRecipePageElement: {
        prototype: HTMLRecipePageElement;
        new (): HTMLRecipePageElement;
    };
    interface HTMLSidebarListItemElement extends Components.SidebarListItem, HTMLStencilElement {
    }
    var HTMLSidebarListItemElement: {
        prototype: HTMLSidebarListItemElement;
        new (): HTMLSidebarListItemElement;
    };
    interface HTMLTopNavElement extends Components.TopNav, HTMLStencilElement {
    }
    var HTMLTopNavElement: {
        prototype: HTMLTopNavElement;
        new (): HTMLTopNavElement;
    };
    interface HTMLElementTagNameMap {
        "list-multiplicator": HTMLListMultiplicatorElement;
        "my-component": HTMLMyComponentElement;
        "recipe-ingredients": HTMLRecipeIngredientsElement;
        "recipe-page": HTMLRecipePageElement;
        "sidebar-list-item": HTMLSidebarListItemElement;
        "top-nav": HTMLTopNavElement;
    }
}
declare namespace LocalJSX {
    interface ListMultiplicator {
        "multiplicator"?: number;
        "onMultiplicatorChanged"?: (event: CustomEvent<any>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface RecipeIngredients {
        "multiplicator"?: number;
    }
    interface RecipePage {
        "five"?: string;
        "four"?: string;
        "image"?: string;
        "one"?: string;
        "three"?: string;
        "title"?: string;
        "two"?: string;
    }
    interface SidebarListItem {
        "kind"?: string;
        "unit"?: string;
        "unitValue"?: number;
    }
    interface TopNav {
    }
    interface IntrinsicElements {
        "list-multiplicator": ListMultiplicator;
        "my-component": MyComponent;
        "recipe-ingredients": RecipeIngredients;
        "recipe-page": RecipePage;
        "sidebar-list-item": SidebarListItem;
        "top-nav": TopNav;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "list-multiplicator": LocalJSX.ListMultiplicator & JSXBase.HTMLAttributes<HTMLListMultiplicatorElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "recipe-ingredients": LocalJSX.RecipeIngredients & JSXBase.HTMLAttributes<HTMLRecipeIngredientsElement>;
            "recipe-page": LocalJSX.RecipePage & JSXBase.HTMLAttributes<HTMLRecipePageElement>;
            "sidebar-list-item": LocalJSX.SidebarListItem & JSXBase.HTMLAttributes<HTMLSidebarListItemElement>;
            "top-nav": LocalJSX.TopNav & JSXBase.HTMLAttributes<HTMLTopNavElement>;
        }
    }
}
