/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddNewRating {
    }
    interface ImageViewer {
        "imgAlt": string;
        "imgUrl": string;
        "imgWidth": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyFooter {
    }
    interface MyRating {
        "headline": string;
        "rate": string;
    }
    interface MySocialShare {
    }
    interface RecipeRatings {
    }
    interface RecipeOverview {
        "btnGoalUrl": string;
        "btnText": string;
        "headline": string;
    }
    interface TitleTitleimage {
        "btnGoalUrl": string;
        "btnText": string;
        "btnVisible": boolean;
        "imageAlt": string;
        "imageUrl": string;
    }
}
declare global {
    interface HTMLAddNewRatingElement extends Components.AddNewRating, HTMLStencilElement {
    }
    var HTMLAddNewRatingElement: {
        prototype: HTMLAddNewRatingElement;
        new (): HTMLAddNewRatingElement;
    }
    interface HTMLImageViewerElement extends Components.ImageViewer, HTMLStencilElement {
    }
    var HTMLImageViewerElement: {
        prototype: HTMLImageViewerElement;
        new (): HTMLImageViewerElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyFooterElement extends Components.MyFooter, HTMLStencilElement {
    }
    var HTMLMyFooterElement: {
        prototype: HTMLMyFooterElement;
        new (): HTMLMyFooterElement;
    };
    interface HTMLMyRatingElement extends Components.MyRating, HTMLStencilElement {
    }
    var HTMLMyRatingElement: {
        prototype: HTMLMyRatingElement;
        new (): HTMLMyRatingElement;
    };
    interface HTMLMySocialShareElement extends Components.MySocialShare, HTMLStencilElement {
    }
    var HTMLMySocialShareElement: {
        prototype: HTMLMySocialShareElement;
        new (): HTMLMySocialShareElement;
    };
    interface HTMLRecipeRatingsElement extends Components.RecipeRatings, HTMLStencilElement {
    }
    var HTMLRecipeRatingsElement: {
        prototype: HTMLRecipeRatingsElement;
        new (): HTMLRecipeRatingsElement;
    }
    interface HTMLRecipeOverviewElement extends Components.RecipeOverview, HTMLStencilElement {
    }
    var HTMLRecipeOverviewElement: {
        prototype: HTMLRecipeOverviewElement;
        new (): HTMLRecipeOverviewElement;
    };
    interface HTMLTitleTitleimageElement extends Components.TitleTitleimage, HTMLStencilElement {
    }
    var HTMLTitleTitleimageElement: {
        prototype: HTMLTitleTitleimageElement;
        new (): HTMLTitleTitleimageElement;
    };
    interface HTMLElementTagNameMap {
        "add-new-rating": HTMLAddNewRatingElement;
        "image-viewer": HTMLImageViewerElement;
        "my-component": HTMLMyComponentElement;
        "my-footer": HTMLMyFooterElement;
        "my-rating": HTMLMyRatingElement;
        "my-social-share": HTMLMySocialShareElement;
        "recipe-ratings": HTMLRecipeRatingsElement;
        "recipe-overview": HTMLRecipeOverviewElement;
        "title-titleimage": HTMLTitleTitleimageElement;
    }
}
declare namespace LocalJSX {
    interface AddNewRating {
        "onButtonClickCancel"?: (event: CustomEvent<any>) => void;
        "onButtonClickOK"?: (event: CustomEvent<any>) => void;
        "onTextChanged"?: (event: CustomEvent<string>) => void;
        "onTitleChanged"?: (event: CustomEvent<string>) => void;
    }
    interface ImageViewer {
        "imgAlt"?: string;
        "imgUrl"?: string;
        "imgWidth"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyFooter {
    }
    interface MyRating {
        "headline"?: string;
        "rate"?: string;
    }
    interface MySocialShare {
    }
    interface RecipeRatings {
        "onAdd"?: (event: CustomEvent<any>) => void;
    }
    interface RecipeOverview {
        "btnGoalUrl"?: string;
        "btnText"?: string;
        "headline"?: string;
    }
    interface TitleTitleimage {
        "btnGoalUrl"?: string;
        "btnText"?: string;
        "btnVisible"?: boolean;
        "imageAlt"?: string;
        "imageUrl"?: string;
    }
    interface IntrinsicElements {
        "add-new-rating": AddNewRating;
        "image-viewer": ImageViewer;
        "my-component": MyComponent;
        "my-footer": MyFooter;
        "my-rating": MyRating;
        "my-social-share": MySocialShare;
        "recipe-ratings": RecipeRatings;
        "recipe-overview": RecipeOverview;
        "title-titleimage": TitleTitleimage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-new-rating": LocalJSX.AddNewRating & JSXBase.HTMLAttributes<HTMLAddNewRatingElement>;
            "image-viewer": LocalJSX.ImageViewer & JSXBase.HTMLAttributes<HTMLImageViewerElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-footer": LocalJSX.MyFooter & JSXBase.HTMLAttributes<HTMLMyFooterElement>;
            "my-rating": LocalJSX.MyRating & JSXBase.HTMLAttributes<HTMLMyRatingElement>;
            "my-social-share": LocalJSX.MySocialShare & JSXBase.HTMLAttributes<HTMLMySocialShareElement>;
            "recipe-ratings": LocalJSX.RecipeRatings & JSXBase.HTMLAttributes<HTMLRecipeRatingsElement>;
            "recipe-overview": LocalJSX.RecipeOverview & JSXBase.HTMLAttributes<HTMLRecipeOverviewElement>;
            "title-titleimage": LocalJSX.TitleTitleimage & JSXBase.HTMLAttributes<HTMLTitleTitleimageElement>;
        }
    }
}
